#define NAME_LENGTH 128
#define VERSION_LENGTH 8
#define DESCRIPTION_LENGTH 512

#define MAX_DEPENDENCIES_PERMITTED 2048

#define MAX_ALGORITHM_TYPE_LENGTH 6
#define MAX_CHECKSUM_LENGTH 512

#define DEPENDENCY_TYPE_LENGTH 24

