.TH man 9 "2024-05-12" "0.1.0" "nekomusume README.9"
.SH Introduction
Welcome to the nekomusume documentation files. I'll dive right into it.
.SH Compatibility
Backwards compatibility with the command line will be attempted.
Backwards compatibility is not guaranteed with the internal libraries. 
.SH See also
.BR TODO
