name: Nekomusume (glibc, dynamic)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run nproc
      run: nproc
    - name: Create skeleton build directory
      run: utils/create-build-skeleton.sh
    - name: Build
      run: make
    - name: Run checks
      run: make tests
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nekomusume-artifact
        path: bins/nekomusume
        compression-level: 0
