name: Nekomusume CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create skeleton build directory
      run: utils/create-build-skeleton.sh
    - name: make
      run: make
