name: Nekomusume CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install musl
      run: sudo apt-get install musl-tools -y
    - name: Run nproc
      run: nproc
    - name: Create skeleton build directory
      run: utils/create-build-skeleton.sh
    - name: Build
      run: make CC=musl-gcc
    - name: Run checks
      run: make tests CC=musl-gcc
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nekomusume-artifact
        path: bins/nekomusume
